import type { Metadata } from "next";
import policy from "@/lib/robots-policy.json";
import type { SEOMeta } from "@/types";

/* One copy of the production origin, shared with robots.ts's policy and with
   scripts/check-robots-policy.mjs. The switch that decides whether the site is
   indexable at all cannot be a value two files each spell for themselves. */
const PRODUCTION_URL = policy.productionUrl;

export const SITE = {
  url: process.env.NEXT_PUBLIC_SITE_URL ?? "http://localhost:3000",
  name: "Yallo Talent",
  brand: "Yallo",
  locales: ["en-GB", "en-AE"] as const,
} as const;

export const isProductionHost =
  process.env.NEXT_PUBLIC_SITE_URL === PRODUCTION_URL;

interface BuildMetadataInput {
  seo: SEOMeta;
  path: string;
}

export function buildMetadata({ seo, path }: BuildMetadataInput): Metadata {
  const url = `${SITE.url}${path}`;
  /* Generated by src/app/og/[[...slug]]/route.tsx at build time, deterministic
     from the same path — never the removed static /images/og-default.jpg,
     which did not exist, so every page previewed broken until a page set its
     own seo.ogImage (none did). */
  const image = seo.ogImage ?? `/og${path === "/" ? "" : path}`;

  return {
    title: seo.title,
    description: seo.description,
    keywords: seo.keywords,
    metadataBase: new URL(SITE.url),
    alternates: {
      canonical: seo.canonical ?? url,
      languages: {
        "en-GB": url,
        "en-AE": url,
      },
    },
    openGraph: {
      title: seo.title,
      description: seo.description,
      url,
      siteName: SITE.name,
      images: [{ url: image, width: 1200, height: 630, alt: seo.title }],
      locale: "en_GB",
      type: "website",
    },
    twitter: {
      card: "summary_large_image",
      title: seo.title,
      description: seo.description,
      images: [image],
    },
    robots: isProductionHost
      ? {
          index: true,
          follow: true,
          googleBot: {
            index: true,
            follow: true,
            "max-image-preview": "large",
            "max-snippet": -1,
          },
        }
      : {
          index: false,
          follow: false,
          googleBot: {
            index: false,
            follow: false,
          },
        },
  };
}
